# Generated by Django 3.0 on 2019-12-04 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitterclone', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweets',
            old_name='TwitterUsers',
            new_name='twitteruser',
        ),
    ]
