# Generated by Django 3.0 on 2019-12-04 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitterclone', '0002_auto_20191204_1633'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tweets',
            new_name='Tweet',
        ),
    ]
