# Generated by Django 2.2.6 on 2019-12-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterclone', '0004_auto_20191206_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='likes',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='retweets',
            field=models.IntegerField(blank=True),
        ),
    ]
