# Generated by Django 2.2.6 on 2019-12-06 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitterclone', '0007_auto_20191206_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twitteruser',
            old_name='username',
            new_name='name',
        ),
    ]
