# Generated by Django 2.2.6 on 2019-12-09 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitterclone', '0008_auto_20191206_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitterclone.Tweet')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitterclone.TwitterUser')),
            ],
        ),
    ]
